Description: >
  Henok Hailemariam
  Udacity Cloud DevOps Engineer Nanodegree
  Project 2: Deploying a High Availability Web App using CloudFormation
  10 September 2020

  This template deploys a VPC, with two public and two private subnets spread 
  across two Availabilty Zones.

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  Outputs:
