Description: >
  Henok Hailemariam
  Udacity Cloud DevOps Engineer Nanodegree
  Project 2: Deploying a High Availability Web App using CloudFormation
  11 September 2020

  The network.yml CloudFormation script in the same directory deploys a VPC,
  with two public and two private subnets. On top of that infrastructure, this
  template deploys two Web Servers in each of the two private subnets.
  Each server is associated with an EBS volume. This script also adds an 
  application load balancer infront of the servers. It also creates a Bastion host
  in a public subnet.


Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: StringParameters:


Resources:
  # instace profile contains the IAM Role name(s) that we want to associate to our auto scaling EC2 Servers
  # never give too much permissions to your EC2 instances! if they get hacked, the permissions get hacked also!
  # in this example, I create a Role called UdacityS3ReadOnlyC2 and just give it a policy of S3 Read-Only Access
  ProfileWithRolesForOurApp:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - UdacityS3ReadOnlyEC2



# Sample UserData
#  #!/bin/bash
#  apt-get update -y
#  apt-get install apache2 -y
#  systemctl start apache2.service
#  cd /var/www/html
#  echo "Udacity Demo Web Server Up and Running!" > index.html


Outputs:

  # TODO: add URL of the load balancer to output
